### ISSUE TITLE
Check against old issues for 2D scatter plot

### ISSUE THREAD

**Issue by marohrdanz** [MD-Anderson-Bioinformatics/ScatterPlotPlugin3D#18]
Check against old issues for related 2D scatter plot plugin.

**Comment by marohrdanz** [comment]
This was the only such issue to fix: d29c9836fec1c75092d433258d8dc6d39c79b242

**Comment by jmelott** [comment]
Can't help you verify this one as it wasn't completely clear to me as to what the issue being fixed was and no way to reproduce issue was listed.

**Comment by marohrdanz** [comment]
It's cool. This GitHub issue was just a reminder for me to go through the issues you had found for a different project and verify they weren't also issues for this project. There was only one of those old issues that was present here, and I fixed it with the above-mentioned commit.
