### ISSUE TITLE
Error in console if user right-click-drags legend element.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/ScatterPlotPlugin3D#23]
Open map, display 3D Plot, right-click and try to drag legend element outside of box legend is in.

Get error in console:
Uncaught TypeError: Cannot read property 'removeChild' of null
    at HTMLCanvasElement.<anonymous> (selectionBox.js:208)
(anonymous) @ selectionBox.js:208

**Comment by marohrdanz** [comment]
This error was actually due to dragging onto the canvas. Addressed by the above-mentioned commit.
