### ISSUE TITLE
Communication between two 3D scatterplot windows can be slow and can stop other features from working.

### ISSUE THREAD

**Issue by jmelott** [MD-Anderson-Bioinformatics/ScatterPlotPlugin3D#30]
Steps to reproduce:
Open larger map like Deprez3000.
Open two 3D scatterplot panes at the same time.
Slowly scroll over different points in one pane (pane 1) for 5 seconds or so.
After a few seconds, the updates of the currently selected point may no longer show up on the other pane (pane 2).
Move mouse over other pane (pane 2) and leave mouse alone.
Highlighted points selected on previous pane will continue to appear for another 15 seconds or more.
During the time that points are slowly appearing, attempts to bring the gear menu or other options on pane 2 will not function correctly.

**Comment by jmelott** [comment]
Note:  Seemed to be hidden at first, but multiple messages appear in console similar to:
vanodi.js:9 [Violation] 'message' handler took 194ms

Additional, but fewer copies of following messages would appear
Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
OrbitControls.js:539 

[Violation] 'setTimeout' handler took 65ms
DetailHeatMapDisplay.js:1312

**Comment by jmelott** [comment]
Still slow with lots of setTimeout messages in console, but doesn't continue on past when user actually moving the mouse or break other parts of app.

**Comment by marohrdanz** [comment]
We'll continue to look for ways to make this faster.
